# Generated by Django 6.0.3 on 2026-03-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htkapp', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_amount',
            field=models.IntegerField(default=0),
        ),
    ]
