# Generated by Django 6.0.3 on 2026-03-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htkapp', '0007_coupon_max_discount_coupon_min_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='htkapp.order'),
        ),
    ]
