# Generated by Django 6.0.3 on 2026-03-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htkapp', '0009_order_name_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
    ]
