# Generated by Django 6.0.3 on 2026-03-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htkapp', '0012_userprofile_address_line1_userprofile_address_line2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
