# Generated by Django 6.0.3 on 2026-03-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htkapp', '0015_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
