# Generated by Django 6.0.3 on 2026-03-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htkapp', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
